apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: spotify-api
          imagePullPolicy: Never
          env:
            - name: SpotifyApi__ClientId
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: client-id
            - name: SpotifyApi__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: spotify-credentials
                  key: client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
      