apiVersion: v1
kind: Service
metadata:
  name: apinpservice-srv
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30098